---
- name: Play
  hosts: master
  vars:
    var1: playvalue
  tasks:
    - name: Task-1
      debug:
        msg: Task-1 msg is {{ var1 }}
      vars:
        var1: value1
    
    - name: Task-2
      debug:
        msg: Task-2 var is {{ var1 }}
