---
- name: With-items Example
  hosts: all
  vars:
    list_items:
      - object1
      - object2
      - object3
  tasks:
    - name: Listing the items
      debug:
        msg: Item is {{ item }}
      with_items: "{{ list_items }}"
